<?php $this->partial('partials/index'); ?>
<table class="table">
    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">prenom-nom</th>
        <th scope="col">niveau-competence</th>
        <th scope="col">prime d'embauche</th>
    </tr>
    </thead>
    <?php if (!empty($collaborateurs)) {
        foreach ($collaborateurs as $collaborateur) { ?>

            <tr>
                <td><?php echo $collaborateur->id; ?></td>
                <td><?php echo $collaborateur->prenom_nom; ?></td>
                <td><?php echo $collaborateur->niveau_competence; ?></td>
                <td><?php echo $collaborateur->prime_embauche; ?></td>
            </tr>
        <?php }
    } else { ?>
        <tr>
            <td colspan="3">Aucun collabo_ trouvé.</td>
        </tr>
    <?php } ?>
</table>
