<!DOCTYPE html>
<html lang="en">
<head>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<div class="container">

    <h1>Vous allez etre rediriger vers votre ancienne page</h1>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Erreur</h5>
            </div>
            <div class="modal-body">
                Non vous ne pouvez pas associer ce     <?php echo $chefDeProjet; ?> avec ce(s) membre(s)
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-primary" href="/test1/equipe">Retour</a>
            </div>
        </div>
    </div>
</div>
</div>
<script>
    // Fonction pour afficher la modal automatiquement lors du chargement de la page
    function showMyModal() {
        $('#exampleModal').modal('show');
    }

    // Appeler la fonction pour afficher la modal lors du chargement de la page
    $(document).ready(function() {
        showMyModal();
    });

    // Ajoutez ici la logique de redirection si nécessaire
    function redirectMe() {
        window.location.href = '/test1/equipe';
    }

    setTimeout(redirectMe, 3000); // Redirection après 3 secondes
</script>
